name: auth_test
description: A new Flutter project, which supports authorization process.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0

  # UI
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2

  # Functional programming
  dartz: ^0.10.0-nullsafety.1
  rxdart: ^0.27.0

  # Auto-gen
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  injectable: ^1.3.0
  auto_route: ^2.1.1


dev_dependencies:
  # Lint
  lint: ^1.5.3

  # Auto-gen
  freezed: ^0.14.1+3
  injectable_generator: ^1.3.0
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.1

  # Build
  build_runner: ^2.0.2

  # Testing
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
